import { Router } from "express";
import { authRouter } from "./auth.routes.js";
import { userRouter } from "./user.routes.js";
import { productRouter } from "./product.routes.js";
import { saleRouter } from "./sale.routes.js";
import { customerRouter } from "./customer.routes.js";
import { cashRegisterRouter } from "./cash-register.routes.js";
import { productTypeRouter } from "./product-type.routes.js";
import { brandRouter } from "./brand.routes.js";
import { pixRouter } from "./pix.routes.js";
import { settingsRouter } from "./settings.routes.js";
import { cardMachineRouter } from "./card-machine.routes.js";
import { controlRouter } from "./control.routes.js";
import { stockMovementRouter } from "./stock-movement.routes.js";
import { notificationRouter } from "./notification.routes.js";
import { dashboardRouter } from "./dashboard.routes.js";
import { printRouter } from "./print.routes.js";
import { backupRouter } from "./backup.routes.js";
import { networkRouter } from "./network.routes.js";
import { transactionRouter } from "./transaction.routes.js";

export const router = Router();

router.use("/auth", authRouter);
router.use("/users", userRouter);
router.use("/products", productRouter);
router.use("/sales", saleRouter);
router.use("/customers", customerRouter);
router.use("/cash-registers", cashRegisterRouter);
router.use("/product-types", productTypeRouter);
router.use("/brands", brandRouter);
router.use("/pix", pixRouter);
router.use("/settings", settingsRouter);
router.use("/card-machines", cardMachineRouter);
router.use("/control", controlRouter);
router.use("/stock-movements", stockMovementRouter);
router.use("/notifications", notificationRouter);
router.use("/print", printRouter);
router.use("/backups", backupRouter);
router.use("/network", networkRouter);
router.use("/transactions", transactionRouter);

router.use("/", dashboardRouter);
